spring.application.name=shipment-service

# Server
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://postgres:5432/shipment_db
spring.datasource.username=postgres
spring.datasource.password=Pardhu@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc=DEBUG