apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-init-script
  namespace: smart-logistics

data:
  init.sql: |
    CREATE DATABASE shipment_db;
    CREATE DATABASE tracking_db;
    CREATE DATABASE warehouse_db;
    CREATE DATABASE notification_db;